{
 "title": "Mailcow Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "container", "label": "container", "query": { "query": "label_values(container)" } },
   { "name": "mailbox", "label": "mailbox", "query": { "query": "label_values(mailbox)" } }
  ]
 },
 "panels": [
  { "title": "Container status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "repeat": "container",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mailcow_container_running{container=~\"$container\"}  ",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Ham rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(mailcow_rspamd_classification{classification=\"ham\"}[5m])",
     "legendFormat": "{{classification}}"
    }
   ]
  },
  {
   "title": "Onderscheid p/e-mail",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mailcow_rspamd_action", "legendFormat": "{{action}}" }
   ]
  },
  {
   "title": "Gescande berichten",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mailcow_rspamd_classification", "legendFormat": "{{classification}}" }
   ]
  },
  {
   "title": "Spam rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(mailcow_rspamd_classification{classification=\"spam\"}[5m])",
     "legendFormat": "spam"
    }
   ]
  },
  { "title": "Mail metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Quarantine > 250 items",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10,mailcow_quarantine_count{recipient=~\"$mailbox\"}) > 250",
     "legendFormat": "{{recipient}}"
    }
   ]
  },
  {
   "title": "mbx > 10k msg",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10,mailcow_mailbox_messages{mailbox=~\"$mailbox\"}) > 10000",
     "legendFormat": "{{mailbox}}"
    }
   ]
  },
  {
   "title": "Mailbox > 3GB",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10,mailcow_mailbox_quota_used{mailbox=~\"$mailbox\"}) > 3172000000",
     "legendFormat": "{{mailbox}}"
    }
   ]
  },
  {
   "title": "Top mailbox usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10,(mailcow_mailbox_quota_used{mailbox=~\"$mailbox\"} / mailcow_mailbox_quota_allowed{mailbox=~\"$mailbox\"} * 100)) > 50",
     "legendFormat": "{{mailbox}}"
    }
   ]
  }
 ]
}